name: Add word
on:
    workflow_dispatch:
        inputs:
            word:
                description: 'A word to add.'
                required: true
                default: ''
            description:
                description: 'Description of the word.'
                required: true
                default: ''
jobs:
    add:
        runs-on: ubuntu-latest
        outputs:
            transformedWord: ${{ steps.transform.outputs.transformedWord }}
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Transform Word
              id: transform
              run: |
                  transformWord() { echo "$1" | sed -e 's/ /-/g' -e 'y/ÜÄÖüäö/uuaaoo/'; }
                  result=$(transformWord "${{ github.event.inputs.word }}")
                  result=$(echo "$result" | tr '[:upper:]' '[:lower:]')
                  echo "transformedWord=$result" >> "$GITHUB_OUTPUT"

            - name: Install
              run: |
                  npm ci

            - name: Add word
              run: |
                  npm run file-from-word "${{ github.event.inputs.word }}" "${{ github.event.inputs.description }}"

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v5
              with:
                  title: 'New word: ${{ github.event.inputs.word }}'
                  branch: 'new_word_${{ needs.add.outputs.transformedWord }}'
                  branch-suffix: 'random'
                  commit-message: 'New word: ${{ github.event.inputs.word }}'
                  add-paths: words/*.mdx
                  assignees: |
                      maksugr
                      ivan-orekhov
                  reviewers: |
                      maksugr
                      ivan-orekhov
