name: Send weekly new words notification
on:
  schedule:
    # at 20:00 on Friday
    - cron:  '0 20 * * 5'
env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
  TWITTER_CLIENT_APP_KEY: ${{ secrets.TWITTER_CLIENT_APP_KEY }}
  TWITTER_CLIENT_APP_SECRET: ${{ secrets.TWITTER_CLIENT_APP_SECRET }}
  TWITTER_CLIENT_ACCESS_TOKEN: ${{ secrets.TWITTER_CLIENT_ACCESS_TOKEN }}
  TWITTER_CLIENT_ACCESS_SECRET: ${{ secrets.TWITTER_CLIENT_ACCESS_SECRET }}
jobs:
  changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install
        run: |
            npm ci
      - name: Send notification
        run: |
            npm run weekly-new-words-notification
