name: Send new word notification
on:
  deployment_status
env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
  TWITTER_CLIENT_APP_KEY: ${{ secrets.TWITTER_CLIENT_APP_KEY }}
  TWITTER_CLIENT_APP_SECRET: ${{ secrets.TWITTER_CLIENT_APP_SECRET }}
  TWITTER_CLIENT_ACCESS_TOKEN: ${{ secrets.TWITTER_CLIENT_ACCESS_TOKEN }}
  TWITTER_CLIENT_ACCESS_SECRET: ${{ secrets.TWITTER_CLIENT_ACCESS_SECRET }}
  REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
  REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
  REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
  REDDIT_REFRESH_TOKEN: ${{ secrets.REDDIT_REFRESH_TOKEN }}
jobs:
  changed_files:
    if: github.event.deployment_status.state == 'success' && github.event.deployment_status.environment == 'Production'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: './words/**'
      - name: Install
        run: |
            npm ci
      - name: Send notification
        run: |
            npm run new-word-notification ${{ steps.changed-files.outputs.added_files }}
