name: Send new word notification
on:
  push:
    branches:
      - main
env:
  TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
  TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
  TWITTER_CLIENT_APP_KEY: ${{ secrets.TWITTER_CLIENT_APP_KEY }}
  TWITTER_CLIENT_APP_SECRET: ${{ secrets.TWITTER_CLIENT_APP_SECRET }}
  TWITTER_CLIENT_ACCESS_TOKEN: ${{ secrets.TWITTER_CLIENT_ACCESS_TOKEN }}
  TWITTER_CLIENT_ACCESS_SECRET: ${{ secrets.TWITTER_CLIENT_ACCESS_SECRET }}
jobs:
  changed_files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          fetch-depth: 0
          files: './words/**'
      - name: Install
        run: |
            npm ci
      - name: Send notification
        run: |
            npm run new_word_notification ${{ steps.changed-files.outputs.added_files }}
